//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digitard.DAL
{
    using System.Runtime.Serialization
    using System;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class Component_has_Property
    {
    [DataMember]
        public int idComponent { get; set; }
    [DataMember]
        public int idProperty { get; set; }
    [DataMember]
        public int idValue { get; set; }
    
    [DataMember]
        public virtual Component Component { get; set; }
    [DataMember]
        public virtual Value Value { get; set; }
    [DataMember]
        public virtual Property Property { get; set; }
    }
}
