//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digitard.DAL
{
    using System.Runtime.Serialization
    using System;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class Country
    {
        public Country()
        {
            this.User = new HashSet<User>();
        }
    
    [DataMember]
        public int idCountry { get; set; }
    [DataMember]
        public string name { get; set; }
    [DataMember]
        public string iso2 { get; set; }
    
    [DataMember]
        public virtual ICollection<User> User { get; set; }
    }
}
