//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digitard.DAL
{
    using System.Runtime.Serialization
    using System;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class User
    {
        public User()
        {
            this.Cart = new HashSet<Cart>();
        }
    
    [DataMember]
        public int idUser { get; set; }
    [DataMember]
        public int idCity { get; set; }
    [DataMember]
        public int idCountry { get; set; }
    [DataMember]
        public int idRole { get; set; }
    [DataMember]
        public string firstname { get; set; }
    [DataMember]
        public string name { get; set; }
    [DataMember]
        public string address { get; set; }
    [DataMember]
        public Nullable<short> streetNumber { get; set; }
    [DataMember]
        public Nullable<short> pc { get; set; }
    [DataMember]
        public string email { get; set; }
    [DataMember]
        public string phoneNumber { get; set; }
    [DataMember]
        public string password { get; set; }
    [DataMember]
        public int salt { get; set; }
    
    [DataMember]
        public virtual ICollection<Cart> Cart { get; set; }
    [DataMember]
        public virtual City City { get; set; }
    [DataMember]
        public virtual Country Country { get; set; }
    [DataMember]
        public virtual Role Role { get; set; }
    }
}
