//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digitard.DAL
{
    using System.Runtime.Serialization
    using System;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class Value
    {
        public Value()
        {
            this.Component_has_Property = new HashSet<Component_has_Property>();
        }
    
    [DataMember]
        public int idValue { get; set; }
    [DataMember]
        public string value1 { get; set; }
    
    [DataMember]
        public virtual ICollection<Component_has_Property> Component_has_Property { get; set; }
    }
}
